version: '3'
x-airflow-common: &airflow-common
    build:
        context: ./container/airflow
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.9.1-python3.11}
    environment: &airflow-common-env
        AIRFLOW__CORE__EXECUTOR: CeleryExecutor
        AIRFLOW__CORE__FERNET_KEY: AnsRXkzo4vgOuE52ftgG83N_RMufcdoMDzJgcTR_3Xw=
        AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS: False
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres:5432/airflow
        AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
        AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    volumes:
        - ./volumes/airflow/dags:/opt/airflow/dags
        - ./volumes/airflow/logs:/opt/airflow/logs
    depends_on:
        - postgres
        - redis

services:
    flink-jobmanager:
        container_name: flink-jobmanager
        build:
            context: ./container/flink/
        command: jobmanager
        ports:
            - '8081:8081'
            - '9249:9249'
        volumes:
            - ./volumes/flink:/opt/flink/code
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
            - TZ=Asia/Bangkok

    flink-taskmanager:
        container_name: flink-taskmanager
        build:
            context: ./container/flink/
        command: taskmanager
        ports:
            - '9250:9249'
        volumes:
            - ./volumes/flink:/opt/flink/code
        scale: 1
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
                taskmanager.numberOfTaskSlots: 2
            - TZ=Asia/Bangkok
        depends_on:
            - flink-jobmanager

    prometheus:
        image: prom/prometheus:v2.37.1
        container_name: prometheus
        ports:
            - '9090:9090'
        volumes:
            - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana:10.3.3
        container_name: grafana
        ports:
            - '3000:3000'
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=grafana
        volumes:
            - ./volumes/grafana/provisioning/:/etc/grafana/provisioning/

    zookeeper:
        image: docker.io/bitnami/zookeeper:3.8
        container_name: zookeeper
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: docker.io/bitnami/kafka:3.4
        container_name: kafka
        ports:
            - '9093:9093'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://:9093
            - KAFKA_CFG_LISTENERS=INSIDE://:9092,OUTSIDE://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper

    postgres:
        image: docker.io/bitnami/postgresql:16
        container_name: postgres
        hostname: postgres
        environment:
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=postgres
            - POSTGRESQL_DATABASE=postgres
            - POSTGRESQL_OTHER_DATABASES=airflow
            - POSTGRESQL_REPLICATION_MODE=master
            - POSTGRESQL_REPLICATION_USER=repl_user
            - POSTGRESQL_REPLICATION_PASSWORD=repl_password
            - POSTGRESQL_LOG_CONNECTIONS=true
        ports:
            - '5432:5432'
        volumes:
            - ./volumes/postgres:/docker-entrypoint-initdb.d

    postgres-slave:
        image: docker.io/bitnami/postgresql:16
        container_name: postgres-slave
        restart: on-failure:5
        environment:
            - POSTGRESQL_PASSWORD=postgres
            - POSTGRESQL_MASTER_HOST=postgres
            - POSTGRESQL_MASTER_PORT_NUMBER=5432
            - POSTGRESQL_REPLICATION_MODE=slave
            - POSTGRESQL_REPLICATION_USER=repl_user
            - POSTGRESQL_REPLICATION_PASSWORD=repl_password
            - POSTGRESQL_LOG_CONNECTIONS=true
            # - POSTGRESQL_PGAUDIT_LOG=READ
        ports:
            - '5433:5432'
        depends_on:
            - postgres

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        restart: always

    airflow-webserver:
        <<: *airflow-common
        container_name: airflow-webserver
        command: webserver
        ports:
            - '8080:8080'
        restart: always

    airflow-scheduler:
        <<: *airflow-common
        container_name: airflow-scheduler
        command: scheduler
        restart: always

    airflow-worker:
        <<: *airflow-common
        container_name: airflow-worker
        command: celery worker
        restart: always

    airflow-init:
        <<: *airflow-common
        container_name: airflow-init
        command: version
        environment:
            <<: *airflow-common-env
            _AIRFLOW_DB_MIGRATE: 'true'
            _AIRFLOW_WWW_USER_CREATE: 'true'
            _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
            _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

    airflow-flower:
        <<: *airflow-common
        container_name: airflow-flower
        command: celery flower
        ports:
            - 5555:5555
        restart: always

    0xweb:
        build:
            context: ./container/0xweb/
        command: python /opt/0xweb/fetch_price.py
        container_name: 0xweb
        restart: on-failure:5
        volumes:
            - ./volumes/0xweb:/opt/0xweb
        depends_on:
            - postgres
            - kafka

    ethereumetl:
        build:
            context: ./container/ethereumetl/
        command: python /opt/ethereumetl/stream.py
        container_name: ethereumetl
        restart: on-failure:5
        volumes:
            - ./volumes/ethereumetl:/opt/ethereumetl
        depends_on:
            - postgres
            - kafka
