{
 "title": "Ethereum",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket_interval", "label": "Interval", "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d" },
   { "name": "tenkan_periods", "query": "9" },
   { "name": "kijun_periods", "query": "26" },
   { "name": "senkou_b_periods", "query": "52" },
   { "name": "macd_fast_periods", "query": "12" },
   { "name": "macd_slow_periods", "query": "26" },
   { "name": "macd_signal_periods", "query": "9" },
   { "name": "macd_smooth_factor", "query": "2" },
   { "name": "jaw_periods", "query": "13" },
   { "name": "jaw_offset", "query": "8" },
   { "name": "teeth_periods", "query": "8" },
   { "name": "teeth_offset", "query": "5" },
   { "name": "lip_periods", "query": "5" },
   { "name": "lip_offset", "query": "3" }
  ]
 },
 "panels": [
  {
   "title": "Ethereum Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  price\nFROM\n  ethereum.block_price\nORDER BY block DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Transactions Count (Last $bucket_interval)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(transaction_count)\r\nFROM\r\n  ethereum.block_price\r\nWHERE block_timestamp BETWEEN current_timestamp - INTERVAL '$bucket_interval' AND current_timestamp;\r\n"
    }
   ]
  },
  { "title": "Model Prediction Result", "type": "timeseries", "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Ethereum Price",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "WITH T AS (  \r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    block,\r\n    price\r\n  FROM ethereum.block_price\r\n)\r\nSELECT MMV.block_timestamp,\r\n  O.price as open,\r\n  high,\r\n  low,\r\n  C.price as close,\r\n  AVG(C.price) OVER (ORDER BY C.block ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS MA7,\r\n  AVG(C.price) OVER (ORDER BY C.block ROWS BETWEEN 24 PRECEDING AND CURRENT ROW) AS MA25,\r\n  AVG(C.price) OVER (ORDER BY C.block ROWS BETWEEN 98 PRECEDING AND CURRENT ROW) AS MA99\r\nFROM\r\n  (\r\n    SELECT block_timestamp,\r\n      MAX(price) AS high,\r\n      MIN(price) AS low\r\n    FROM T\r\n    GROUP BY block_timestamp\r\n  ) MMV,\r\n  (\r\n    SELECT DISTINCT ON (block_timestamp) block_timestamp, block, price\r\n    FROM T\r\n    ORDER BY block_timestamp, block DESC\r\n  ) C,\r\n  (\r\n    SELECT DISTINCT ON (block_timestamp) block_timestamp, block, price\r\n    FROM T\r\n    ORDER BY block_timestamp, block\r\n  ) O\r\nWHERE MMV.block_timestamp = C.block_timestamp AND MMV.block_timestamp = O.block_timestamp\r\nORDER BY MMV.block_timestamp\r\nLIMIT 100000"
    }
   ]
  },
  { "title": "On-chain Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Transactions Count (MA7 of $bucket_interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "WITH T AS (\r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    SUM(transaction_count) AS transaction_count\r\n  FROM ethereum.block_price\r\n  GROUP BY date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01')\r\n)\r\nSELECT block_timestamp,\r\n  AVG(transaction_count) OVER (ORDER BY block_timestamp ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS transaction_count\r\nFROM T;\r\n"
    }
   ]
  },
  {
   "title": "ETH Burned (MA7 of $bucket_interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "rawSql": "WITH T AS (\r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    SUM(burned_eth) AS burned_eth\r\n  FROM ethereum.block_price\r\n  GROUP BY date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01')\r\n)\r\nSELECT block_timestamp,\r\n  AVG(burned_eth) OVER (ORDER BY block_timestamp ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS burned_eth\r\nFROM T;\r\n"
    }
   ]
  },
  {
   "title": "Block Validator Revenue (MA7 of $bucket_interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "WITH T AS (\r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    block,\r\n    static_rewards_eth,\r\n    validator_withdrawals_eth,\r\n    price\r\n  FROM ethereum.block_price\r\n),\r\nTX AS (\r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    SUM(tx_fees_eth) AS tx_fees_eth\r\n  FROM ethereum.transactions\r\n  GROUP BY date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01')\r\n)\r\nSELECT R.block_timestamp,\r\n  AVG(static_rewards_eth) OVER (ORDER BY R.block_timestamp ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) * price AS \"Static Rewards\",\r\n  AVG(validator_withdrawals_eth) OVER (ORDER BY R.block_timestamp ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) * price AS \"Validator Withdrawals\",\r\n  TX.tx_fees_eth * price AS \"Transaction Fees\"\r\nFROM TX,\r\n  (\r\n    SELECT block_timestamp,\r\n      SUM(static_rewards_eth) AS static_rewards_eth,\r\n      SUM(validator_withdrawals_eth) AS validator_withdrawals_eth\r\n    FROM T\r\n    GROUP BY block_timestamp\r\n  ) R,\r\n  (\r\n    SELECT DISTINCT ON (block_timestamp) block_timestamp, block, price\r\n    FROM T\r\n    ORDER BY block_timestamp, block DESC\r\n  ) C\r\nWHERE R.block_timestamp = C.block_timestamp AND R.block_timestamp = TX.block_timestamp\r\n"
    }
   ]
  },
  {
   "title": "Trading Volume (MA7 of $bucket_interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "WITH T AS (\r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    SUM(volume_eth) AS volume\r\n  FROM ethereum.transactions\r\n  GROUP BY date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01')\r\n),\r\nBP AS (\r\n  SELECT DISTINCT ON (block_timestamp) block_timestamp, block, price\r\n  FROM (\r\n    SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n      block,\r\n      price\r\n    FROM ethereum.block_price\r\n  )\r\n  ORDER BY block_timestamp, block DESC\r\n)\r\nSELECT T.block_timestamp,\r\n  AVG(volume) OVER (ORDER BY T.block_timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) * price AS volume\r\nFROM T, BP\r\nWHERE T.block_timestamp = BP.block_timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Active Addresses (MA7 of $bucket_interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "rawSql": "WITH T AS (\r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    SUM(active_address) AS active_address\r\n  FROM ethereum.transactions\r\n  GROUP BY date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01')\r\n)\r\nSELECT block_timestamp,\r\n  AVG(active_address) OVER (ORDER BY block_timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS active_address\r\nFROM T;\r\n"
    }
   ]
  },
  {
   "title": "Average Gas Price (MA7 of $bucket_interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "targets": [
    {
     "rawSql": "WITH T AS (\r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    SUM(avg_gas_price_gwei) AS avg_gas_price_gwei\r\n  FROM ethereum.transactions\r\n  GROUP BY date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01')\r\n)\r\nSELECT block_timestamp,\r\n  AVG(avg_gas_price_gwei) OVER (ORDER BY block_timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_gas_price_gwei\r\nFROM T;\r\n"
    }
   ]
  },
  {
   "title": "Average Block Size (MA7 of $bucket_interval)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH T AS (\r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    AVG(size) AS size\r\n  FROM ethereum.block_price\r\n  GROUP BY date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01')\r\n)\r\nSELECT\r\n  AVG(size) OVER (ORDER BY block_timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)\r\nFROM T\r\nORDER BY block_timestamp\r\nLIMIT 100000;\r\n"
    }
   ]
  },
  {
   "title": "Average Gas Used Percentage (MA7 of $bucket_interval)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH T AS (\r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    AVG(CAST(gas_used_wei AS DECIMAL(14,2)) / CAST(gas_limit_wei AS DECIMAL(14,2))) AS gas_used_percentage\r\n  FROM ethereum.block_price\r\n  GROUP BY date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01')\r\n)\r\nSELECT\r\n  AVG(gas_used_percentage) OVER (ORDER BY block_timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)\r\nFROM T\r\nORDER BY block_timestamp\r\nLIMIT 100000;\r\n"
    }
   ]
  },
  {
   "title": "Average Base Fee (MA7 of $bucket_interval)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH T AS (\r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    AVG(base_fee_per_gas_gwei) AS base_fee_per_gas_gwei\r\n  FROM ethereum.block_price\r\n  GROUP BY date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01')\r\n)\r\nSELECT\r\n  AVG(base_fee_per_gas_gwei) OVER (ORDER BY block_timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)\r\nFROM T\r\nORDER BY block_timestamp\r\nLIMIT 100000;\r\n"
    }
   ]
  },
  { "title": "Technical Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Ichimoku Cloud",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "WITH T AS (  \r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    block,\r\n    price\r\n  FROM ethereum.block_price\r\n),\r\nOHLC AS (\r\n  SELECT MMV.block_timestamp,\r\n    O.price as open,\r\n    high,\r\n    low,\r\n    C.price as close\r\n  FROM\r\n    (\r\n      SELECT block_timestamp,\r\n        MAX(price) AS high,\r\n        MIN(price) AS low\r\n      FROM T\r\n      GROUP BY block_timestamp\r\n    ) MMV,\r\n    (\r\n      SELECT DISTINCT ON (block_timestamp) block_timestamp, block, price\r\n      FROM T\r\n      ORDER BY block_timestamp, block DESC\r\n    ) C,\r\n    (\r\n      SELECT DISTINCT ON (block_timestamp) block_timestamp, block, price\r\n      FROM T\r\n      ORDER BY block_timestamp, block\r\n    ) O\r\n  WHERE MMV.block_timestamp = C.block_timestamp AND MMV.block_timestamp = O.block_timestamp\r\n  ORDER BY MMV.block_timestamp\r\n  LIMIT 100000\r\n),\r\nICHIMOKU AS (\r\n  SELECT block_timestamp,\r\n    (MAX(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $tenkan_periods - 1 PRECEDING AND CURRENT ROW) + \r\n      MIN(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $tenkan_periods - 1 PRECEDING AND CURRENT ROW)) / 2 \r\n      AS \"Tenkan Sen\",\r\n    (MAX(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $kijun_periods - 1 PRECEDING AND CURRENT ROW) + \r\n      MIN(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $kijun_periods - 1 PRECEDING AND CURRENT ROW)) / 2 \r\n      AS \"Kijun Sen\",\r\n    (MAX(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $senkou_b_periods - 1 PRECEDING AND CURRENT ROW) + \r\n      MIN(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $senkou_b_periods - 1 PRECEDING AND CURRENT ROW)) / 2 \r\n      AS \"Senkou Span B\",\r\n    LEAD(close, $kijun_periods) OVER (ORDER BY block_timestamp) AS \"Chikou Span\"\r\n  FROM OHLC\r\n)\r\nSELECT OHLC.block_timestamp, open, high, low, close,\r\n  \"Tenkan Sen\", \"Kijun Sen\", (\"Tenkan Sen\" + \"Kijun Sen\") / 2 AS \"Senkou Span A\", \"Senkou Span B\", \"Chikou Span\"\r\nFROM OHLC, ICHIMOKU\r\nWHERE OHLC.block_timestamp = ICHIMOKU.block_timestamp"
    }
   ]
  },
  {
   "title": "Moving Average Convergence / Divergence (MACD)",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "WITH T AS (  \r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    block,\r\n    price\r\n  FROM ethereum.block_price\r\n),\r\nOHLC AS (\r\n  SELECT MMV.block_timestamp,\r\n    O.price as open,\r\n    high,\r\n    low,\r\n    C.price as close\r\n  FROM\r\n    (\r\n      SELECT block_timestamp,\r\n        MAX(price) AS high,\r\n        MIN(price) AS low\r\n      FROM T\r\n      GROUP BY block_timestamp\r\n    ) MMV,\r\n    (\r\n      SELECT DISTINCT ON (block_timestamp) block_timestamp, block, price\r\n      FROM T\r\n      ORDER BY block_timestamp, block DESC\r\n    ) C,\r\n    (\r\n      SELECT DISTINCT ON (block_timestamp) block_timestamp, block, price\r\n      FROM T\r\n      ORDER BY block_timestamp, block\r\n    ) O\r\n  WHERE MMV.block_timestamp = C.block_timestamp AND MMV.block_timestamp = O.block_timestamp\r\n  ORDER BY MMV.block_timestamp\r\n  LIMIT 100000\r\n),\r\nMACD AS (\r\n  SELECT block_timestamp,\r\n    (close - AVG(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $macd_fast_periods PRECEDING AND 1 PRECEDING)) * \r\n      ($macd_smooth_factor / (1 + $macd_fast_periods)) + \r\n      AVG(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $macd_fast_periods PRECEDING AND 1 PRECEDING)\r\n    AS fast_ema,\r\n    (close - AVG(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $macd_slow_periods PRECEDING AND 1 PRECEDING)) * \r\n      ($macd_smooth_factor / (1 + $macd_slow_periods)) +\r\n      AVG(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $macd_slow_periods PRECEDING AND 1 PRECEDING)\r\n    AS slow_ema\r\n  FROM OHLC\r\n)\r\nSELECT OHLC.block_timestamp, open, high, low, close, \r\n  fast_ema - slow_ema AS \"MACD\",\r\n  (fast_ema - slow_ema - AVG(fast_ema - slow_ema) OVER (ORDER BY OHLC.block_timestamp ROWS BETWEEN $macd_signal_periods PRECEDING AND 1 PRECEDING)) * \r\n    ($macd_smooth_factor / (1 + $macd_signal_periods)) +\r\n    AVG(fast_ema - slow_ema) OVER (ORDER BY OHLC.block_timestamp ROWS BETWEEN $macd_signal_periods PRECEDING AND 1 PRECEDING)\r\n  AS \"Signal Line\"\r\nFROM OHLC, MACD\r\nWHERE OHLC.block_timestamp = MACD.block_timestamp\r\n"
    }
   ]
  },
  {
   "title": "MACD Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "WITH C AS (\r\n  SELECT DISTINCT ON (block_timestamp) block_timestamp, \r\n    block, \r\n    price AS close\r\n  FROM (\r\n    SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n      block,\r\n      price\r\n    FROM ethereum.block_price\r\n  )\r\n  ORDER BY block_timestamp, block DESC\r\n  LIMIT 100000\r\n),\r\nEMA AS (\r\n  SELECT block_timestamp,\r\n    (close - AVG(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $macd_fast_periods PRECEDING AND 1 PRECEDING)) * \r\n      ($macd_smooth_factor / (1 + $macd_fast_periods)) + \r\n      AVG(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $macd_fast_periods PRECEDING AND 1 PRECEDING)\r\n    AS fast_ema,\r\n    (close - AVG(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $macd_slow_periods PRECEDING AND 1 PRECEDING)) * \r\n      ($macd_smooth_factor / (1 + $macd_slow_periods)) +\r\n      AVG(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $macd_slow_periods PRECEDING AND 1 PRECEDING)\r\n    AS slow_ema\r\n  FROM C\r\n),\r\nMACD AS (\r\n  SELECT C.block_timestamp,\r\n    fast_ema - slow_ema AS macd,\r\n    (fast_ema - slow_ema - AVG(fast_ema - slow_ema) OVER (ORDER BY C.block_timestamp ROWS BETWEEN $macd_signal_periods PRECEDING AND 1 PRECEDING)) * \r\n      ($macd_smooth_factor / (1 + $macd_signal_periods)) +\r\n      AVG(fast_ema - slow_ema) OVER (ORDER BY C.block_timestamp ROWS BETWEEN $macd_signal_periods PRECEDING AND 1 PRECEDING)\r\n    AS signal_line\r\n  FROM C, EMA\r\n  WHERE C.block_timestamp = EMA.block_timestamp\r\n)\r\nSELECT MACD.block_timestamp, \r\n  pos_diff AS \"Positive Difference\", neg_diff AS \"Negative Difference\"\r\nFROM MACD\r\n  LEFT JOIN\r\n  (\r\n    SELECT block_timestamp,\r\n      macd - signal_line AS pos_diff\r\n    FROM MACD\r\n    WHERE macd - signal_line > 0\r\n  ) POS\r\n  ON MACD.block_timestamp = POS.block_timestamp\r\n  LEFT JOIN\r\n  (\r\n    SELECT block_timestamp,\r\n      macd - signal_line AS neg_diff\r\n    FROM MACD\r\n    WHERE macd - signal_line < 0\r\n  ) NEG\r\n  ON MACD.block_timestamp = NEG.block_timestamp"
    }
   ]
  },
  {
   "title": "Williams Alligator",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "rawSql": "WITH T AS (  \r\n  SELECT date_bin('$bucket_interval', block_timestamp, TIMESTAMP '2001-01-01') AS block_timestamp,\r\n    block,\r\n    price\r\n  FROM ethereum.block_price\r\n),\r\nOHLC AS (\r\n  SELECT MMV.block_timestamp,\r\n    O.price as open,\r\n    high,\r\n    low,\r\n    C.price as close\r\n  FROM\r\n    (\r\n      SELECT block_timestamp,\r\n        MAX(price) AS high,\r\n        MIN(price) AS low\r\n      FROM T\r\n      GROUP BY block_timestamp\r\n    ) MMV,\r\n    (\r\n      SELECT DISTINCT ON (block_timestamp) block_timestamp, block, price\r\n      FROM T\r\n      ORDER BY block_timestamp, block DESC\r\n    ) C,\r\n    (\r\n      SELECT DISTINCT ON (block_timestamp) block_timestamp, block, price\r\n      FROM T\r\n      ORDER BY block_timestamp, block\r\n    ) O\r\n  WHERE MMV.block_timestamp = C.block_timestamp AND MMV.block_timestamp = O.block_timestamp\r\n  ORDER BY MMV.block_timestamp\r\n  LIMIT 100000\r\n)\r\nSELECT OHLC.block_timestamp, open, high, low, close,\r\n  AVG(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $jaw_periods + $jaw_offset PRECEDING AND $jaw_offset PRECEDING) AS \"Jaw\",\r\n  AVG(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $teeth_periods + $teeth_offset PRECEDING AND $teeth_offset PRECEDING) AS \"Teeth\",\r\n  AVG(close) OVER (ORDER BY block_timestamp ROWS BETWEEN $lip_periods + $lip_offset PRECEDING AND $lip_offset PRECEDING) AS \"Lips\"\r\nFROM OHLC"
    }
   ]
  },
  { "title": "Raw Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Latest block_price Data",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM\n  ethereum.block_price\nORDER BY block DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "Latest transactions Data",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT block_timestamp, avg_gas_price_gwei, tx_fees_eth, volume_eth, active_address\r\nFROM\r\n  ethereum.transactions\r\nORDER BY minute_group_id DESC\r\nLIMIT 5;\r\n"
    }
   ]
  }
 ]
}