{
 "title": "Flink Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Flink - CPU Load",
   "type": "timeseries",
   "description": "The recent CPU usage of the JVM",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load{host=\"jobmanager\"}*100",
     "legendFormat": "Job Manager CPU Load"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load{host=\"172_18_0_6\"}*100",
     "legendFormat": "Task Manager CPU Load"
    }
   ]
  },
  {
   "title": "Flink - Job Manager Memory Usage",
   "type": "timeseries",
   "description": "The amount of job manager used memory in megabytes",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used{host=\"jobmanager\"}/1024/1024",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used{host=\"jobmanager\"}/1024/1024",
     "legendFormat": "Non-Heap Used"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed{host=\"jobmanager\"}/1024/1024",
     "legendFormat": "Direct Memory Used"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Metaspace_Used{host=\"jobmanager\"}/1024/1024",
     "legendFormat": "Metaspace Used"
    }
   ]
  },
  {
   "title": "Flink - Task Manager Memory Usage",
   "type": "timeseries",
   "description": "The amount of task manager used memory in megabytes",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{host=\"172_18_0_6\"}/1000000",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Max{host=\"172_18_0_6\"}/1000000",
     "legendFormat": "Non-Heap Used"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{host=\"172_18_0_6\"}/1000000",
     "legendFormat": "Direct Memory Used"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Metaspace_Used{host=\"172_18_0_6\"}/1000000",
     "legendFormat": "Metaspace Used"
    }
   ]
  },
  {
   "title": "Flink - Running Jobs",
   "type": "stat",
   "description": "The number of running jobs",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs{host=\"jobmanager\"}"
    }
   ]
  },
  {
   "title": "Flink - # of Task Manager",
   "type": "stat",
   "description": "The number of registered task managers",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers{host=\"jobmanager\"}",
     "legendFormat": "Registered Task Manager"
    }
   ]
  },
  {
   "title": "Kafka Consumer - Records Consumed Rate",
   "type": "timeseries",
   "description": "Average number of records consumed per second for a specific topic or across all topics",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{host=\"172_18_0_6\"}",
     "legendFormat": "Records Consumed Rate"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_rate{host=\"172_18_0_6\"}",
     "legendFormat": "Bytes Consumed Rate"
    }
   ]
  },
  {
   "title": "Kafka Consumer - Latency",
   "type": "timeseries",
   "description": "The average number of outgoing bytes sent per second",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_fetch_latency_avg{host=\"172_18_0_6\"}",
     "legendFormat": "Avg. Fetch Latency"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_commit_latency_avg{host=\"172_18_0_6\"}",
     "legendFormat": "Avg. Commit Latency"
    }
   ]
  },
  {
   "title": "Kafka Consumer - Fetch Rate",
   "type": "timeseries",
   "description": "Number of fetch requests per second from the consumer",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_fetch_rate{host=\"172_18_0_6\"}"
    }
   ]
  },
  {
   "title": "Flink - Job Uptime (Hour)",
   "type": "stat",
   "description": "The time that the job has been running without interruption",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{host=\"jobmanager\"}/1000/60/60",
     "legendFormat": "Uptime (Hour)"
    }
   ]
  },
  {
   "title": "Flink - Job Failing Time (s)",
   "type": "stat",
   "description": "For jobs currently in a failing/recovering situation, the time elapsed during this outage",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_failingTime{host=\"jobmanager\"}/1000",
     "legendFormat": "Job Failing Time (s)"
    }
   ]
  }
 ]
}